# Web node
web:
  extends:
    file: services/services.yml
    service: web
  links:
    - cli
  ports:
    - 80:80
# CLI node
cli:
  extends:
    file: services/services.yml
    service: cli
  links:
    - db

# DB node
db:
  extends:
    file: services/services.yml
    service: db
