# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/drude for more information and documentation.

# Web node
web:
  hostname: web
  image: blinkreaction/drupal-apache:2.2-stable
  volumes:
    # Project root folder mapping
    - &project_root "../:/var/www"

# DB node
db:
  hostname: db
  image: blinkreaction/drupal-mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
  volumes:
    - "../mysql_data:/var/lib/mysql"

# CLI node
# Used for all console commands and tools.
cli:
  hostname: cli
  image: blinkreaction/drupal-cli:php7
  volumes:
    - *project_root
    - "./etc/php5/php.ini:/etc/php/7.0/fpm/conf.d/z_php.ini"
    - "./etc/php5/php-cli.ini:/etc/php/7.0/cli/conf.d/z_php.ini"
    - "./etc/mysql/my.cnf:/etc/my.cnf.d/drupal.cnf"
    - "../data_dumps:/data_dumps"

# Varnish node
varnish:
  hostname: varnish
  image: blinkreaction/drupal-varnish:3.0-stable
#  volumes:
#    - "./etc/varnish/default.vcl:/opt/default.vcl"

# Selenium node
browser:
  hostname: browser
  image: selenium/standalone-chrome
